services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - /home/n8n/data:/home/node/.n8n
    environment:
      GENERIC_TIMEZONE: "Etc/UTC"
      TZ: "Etc/UTC"
      N8N_SECURE_COOKIE: "false"
