services:
  mariadb:
    image: mariadb:12.3.3
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3307:3306"
    volumes:
      - /home/mariadb/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "##CREATE_PASSWORD##"
      MARIADB_DATABASE: "app"
      MARIADB_USER: "app"
      MARIADB_PASSWORD: "##CREATE_PASSWORD##"
      TZ: "Etc/UTC"
